name: Monthly TLD Update

on:
  schedule:
    # Runs at 00:00 EST on the 1st day of every month
    - cron: '0 5 1 * *'
  workflow_dispatch:

jobs:
  update-tld:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      did_update: ${{ steps.check_changes.outputs.changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
            token: ${{ secrets.TLD_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests
          pip install .

      - name: Run update script
        run: python -m pyrolysate.cli --update -o ./pyrolysate/tld.txt

      - name: Commit and push changes
        id: check_changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # TLD data before query
          git show HEAD:pyrolysate/tld.txt | tail -n +5 > old_data.tmp
          # TLD data after query
          tail -n +5 pyrolysate/tld.txt > new_data.tmp

          if cmp -s old_data.tmp new_data.tmp; then
            echo "No TLD changes. Skipping commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected. Bumping pyproject version..."
            pip install toml build
            python bump_version.py
            rm -rf dist/
            python -m build
            echo "TLD change detected. Committing..."
            git add pyrolysate/tld.txt pyproject.toml
            git commit -m "chore: monthly update of IANA TLD list"
            git push

            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  trigger-publish:
    needs: update-tld
    if: needs.update-tld.outputs.did_update == 'true'
    uses: ./.github/workflows/python-publish.yml 
    secrets: inherit
